MISPDEV-26: Integrate AdminTool and propertySynchronizer utilities into the source repository
nordic-institute/misp2 pull request #3
Opened 2022-09-02 11:20 UTC by raits

JIRA ticket: https://nordic-institute.atlassian.net/browse/MISPDEV-26

2022-09-05 05:14 UTC, petkivim requested changes
Currently, the Admin Tool related documentation seems to be available here:

https://github.com/nordic-institute/misp2/blob/main/docs/misp2_installation_manual_18.04.md#61-administration-of-misp2-administrator-accounts-from-the-command-line

Maybe consider moving it to `utils/admin-tool/manual.md` and referencing it from the installation manual and Admin Tool readme (`utils/admin-tool/readme.md`). In that way, the approach would be consistent with the Property Synchronizer. 

Also, the Property Synchronizer manual (`utils/property-synchronizer/manual.md`) isn't currently referenced from any other document in the repo (except readme). Is there a place in the documentation where the tool could be mentioned, e.g., installation guide or manager guide?

2022-09-05 05:17 UTC, petkivim commented on utils/property-synchronizer/manual.md
> +# MISP2 Installation and Configuration Guide
This should probably be:

> MISP2 Property Synchronizer Manual

2022-09-05 05:18 UTC, petkivim commented on utils/property-synchronizer/readme.md
> +# PropertySynchronizer
This should probably be:

> Property Synchronizer

2022-09-07 07:54 UTC, raits commented on utils/property-synchronizer/readme.md
> +# PropertySynchronizer
Fixed.

2022-09-07 07:54 UTC, raits commented on utils/property-synchronizer/manual.md
> +# MISP2 Installation and Configuration Guide
Fixed.

2022-09-07 07:56 UTC, raits commented
> Currently, the Admin Tool related documentation seems to be available here:
> 
> https://github.com/nordic-institute/misp2/blob/main/docs/misp2_installation_manual_18.04.md#61-administration-of-misp2-administrator-accounts-from-the-command-line
> 
> Maybe consider moving it to `utils/admin-tool/manual.md` and referencing it from the installation manual and Admin Tool readme (`utils/admin-tool/readme.md`). Also, it should be referenced from `docker-dev/readme.md`. In that way, the approach would be consistent with the Property Synchronizer.
> 
> Also, the Property Synchronizer manual (`utils/property-synchronizer/manual.md`) isn't currently referenced from any other document in the repo (except readme). Is there a place in the documentation where the tool could be mentioned, e.g., installation guide or manager guide?

Migrated the Admin Tool manual to its own file and added links.

I would leave the Property Synchronizer as it is. It is more of an implementation detail and is used only by the installation script. There should be no need for the user to do anything with it, but good to have the manual for developers that might need to understand what it is supposed to do.

2022-09-07 09:32 UTC, petkivim approved these changes
Looks good to me.

2022-09-08 07:27 UTC, merged